// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: course.proto

package course

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Course struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	InstructorId  int64                  `protobuf:"varint,4,opt,name=instructor_id,json=instructorId,proto3" json:"instructor_id,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,5,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	IsPublished   bool                   `protobuf:"varint,7,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Course) Reset() {
	*x = Course{}
	mi := &file_course_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Course) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Course) ProtoMessage() {}

func (x *Course) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Course.ProtoReflect.Descriptor instead.
func (*Course) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{0}
}

func (x *Course) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Course) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Course) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Course) GetInstructorId() int64 {
	if x != nil {
		return x.InstructorId
	}
	return 0
}

func (x *Course) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *Course) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Course) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

type Section struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CourseId      int64                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	OrderIndex    int32                  `protobuf:"varint,4,opt,name=order_index,json=orderIndex,proto3" json:"order_index,omitempty"`
	Lessons       []*Lesson              `protobuf:"bytes,5,rep,name=lessons,proto3" json:"lessons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Section) Reset() {
	*x = Section{}
	mi := &file_course_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Section) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Section) ProtoMessage() {}

func (x *Section) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Section.ProtoReflect.Descriptor instead.
func (*Section) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{1}
}

func (x *Section) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Section) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *Section) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Section) GetOrderIndex() int32 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

func (x *Section) GetLessons() []*Lesson {
	if x != nil {
		return x.Lessons
	}
	return nil
}

type Lesson struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SectionId     int64                  `protobuf:"varint,2,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	LessonType    string                 `protobuf:"bytes,4,opt,name=lesson_type,json=lessonType,proto3" json:"lesson_type,omitempty"`
	ContentUrl    string                 `protobuf:"bytes,5,opt,name=content_url,json=contentUrl,proto3" json:"content_url,omitempty"`
	OrderIndex    int32                  `protobuf:"varint,6,opt,name=order_index,json=orderIndex,proto3" json:"order_index,omitempty"`
	IsCompleted   bool                   `protobuf:"varint,7,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lesson) Reset() {
	*x = Lesson{}
	mi := &file_course_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lesson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lesson) ProtoMessage() {}

func (x *Lesson) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lesson.ProtoReflect.Descriptor instead.
func (*Lesson) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{2}
}

func (x *Lesson) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Lesson) GetSectionId() int64 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

func (x *Lesson) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Lesson) GetLessonType() string {
	if x != nil {
		return x.LessonType
	}
	return ""
}

func (x *Lesson) GetContentUrl() string {
	if x != nil {
		return x.ContentUrl
	}
	return ""
}

func (x *Lesson) GetOrderIndex() int32 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

func (x *Lesson) GetIsCompleted() bool {
	if x != nil {
		return x.IsCompleted
	}
	return false
}

type CreateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	InstructorId  int64                  `protobuf:"varint,3,opt,name=instructor_id,json=instructorId,proto3" json:"instructor_id,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,5,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseRequest) Reset() {
	*x = CreateCourseRequest{}
	mi := &file_course_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseRequest) ProtoMessage() {}

func (x *CreateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseRequest.ProtoReflect.Descriptor instead.
func (*CreateCourseRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCourseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCourseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCourseRequest) GetInstructorId() int64 {
	if x != nil {
		return x.InstructorId
	}
	return 0
}

func (x *CreateCourseRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateCourseRequest) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

type CreateCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course        *Course                `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseResponse) Reset() {
	*x = CreateCourseResponse{}
	mi := &file_course_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseResponse) ProtoMessage() {}

func (x *CreateCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseResponse.ProtoReflect.Descriptor instead.
func (*CreateCourseResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCourseResponse) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

type CreateSectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	OrderIndex    int32                  `protobuf:"varint,3,opt,name=order_index,json=orderIndex,proto3" json:"order_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSectionRequest) Reset() {
	*x = CreateSectionRequest{}
	mi := &file_course_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSectionRequest) ProtoMessage() {}

func (x *CreateSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSectionRequest.ProtoReflect.Descriptor instead.
func (*CreateSectionRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSectionRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *CreateSectionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSectionRequest) GetOrderIndex() int32 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

type CreateSectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Section       *Section               `protobuf:"bytes,1,opt,name=section,proto3" json:"section,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSectionResponse) Reset() {
	*x = CreateSectionResponse{}
	mi := &file_course_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSectionResponse) ProtoMessage() {}

func (x *CreateSectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSectionResponse.ProtoReflect.Descriptor instead.
func (*CreateSectionResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSectionResponse) GetSection() *Section {
	if x != nil {
		return x.Section
	}
	return nil
}

type CreateLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionId     int64                  `protobuf:"varint,1,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	LessonType    string                 `protobuf:"bytes,3,opt,name=lesson_type,json=lessonType,proto3" json:"lesson_type,omitempty"`
	ContentUrl    string                 `protobuf:"bytes,4,opt,name=content_url,json=contentUrl,proto3" json:"content_url,omitempty"`
	OrderIndex    int32                  `protobuf:"varint,5,opt,name=order_index,json=orderIndex,proto3" json:"order_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLessonRequest) Reset() {
	*x = CreateLessonRequest{}
	mi := &file_course_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLessonRequest) ProtoMessage() {}

func (x *CreateLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLessonRequest.ProtoReflect.Descriptor instead.
func (*CreateLessonRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{7}
}

func (x *CreateLessonRequest) GetSectionId() int64 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

func (x *CreateLessonRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateLessonRequest) GetLessonType() string {
	if x != nil {
		return x.LessonType
	}
	return ""
}

func (x *CreateLessonRequest) GetContentUrl() string {
	if x != nil {
		return x.ContentUrl
	}
	return ""
}

func (x *CreateLessonRequest) GetOrderIndex() int32 {
	if x != nil {
		return x.OrderIndex
	}
	return 0
}

type CreateLessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lesson        *Lesson                `protobuf:"bytes,1,opt,name=lesson,proto3" json:"lesson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLessonResponse) Reset() {
	*x = CreateLessonResponse{}
	mi := &file_course_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLessonResponse) ProtoMessage() {}

func (x *CreateLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLessonResponse.ProtoReflect.Descriptor instead.
func (*CreateLessonResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{8}
}

func (x *CreateLessonResponse) GetLesson() *Lesson {
	if x != nil {
		return x.Lesson
	}
	return nil
}

type GetCoursesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	MinPrice      float64                `protobuf:"fixed64,4,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      float64                `protobuf:"fixed64,5,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	SortBy        string                 `protobuf:"bytes,6,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	InstructorId  int64                  `protobuf:"varint,7,opt,name=instructor_id,json=instructorId,proto3" json:"instructor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoursesRequest) Reset() {
	*x = GetCoursesRequest{}
	mi := &file_course_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoursesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursesRequest) ProtoMessage() {}

func (x *GetCoursesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursesRequest.ProtoReflect.Descriptor instead.
func (*GetCoursesRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{9}
}

func (x *GetCoursesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCoursesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetCoursesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetCoursesRequest) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *GetCoursesRequest) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *GetCoursesRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *GetCoursesRequest) GetInstructorId() int64 {
	if x != nil {
		return x.InstructorId
	}
	return 0
}

type GetCoursesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courses       []*Course              `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoursesResponse) Reset() {
	*x = GetCoursesResponse{}
	mi := &file_course_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoursesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursesResponse) ProtoMessage() {}

func (x *GetCoursesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursesResponse.ProtoReflect.Descriptor instead.
func (*GetCoursesResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{10}
}

func (x *GetCoursesResponse) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

func (x *GetCoursesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetCoursesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCoursesResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type GetCourseDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseDetailsRequest) Reset() {
	*x = GetCourseDetailsRequest{}
	mi := &file_course_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseDetailsRequest) ProtoMessage() {}

func (x *GetCourseDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetCourseDetailsRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{11}
}

func (x *GetCourseDetailsRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *GetCourseDetailsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetCourseDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course        *Course                `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	Sections      []*Section             `protobuf:"bytes,2,rep,name=sections,proto3" json:"sections,omitempty"`
	IsEnrolled    bool                   `protobuf:"varint,3,opt,name=is_enrolled,json=isEnrolled,proto3" json:"is_enrolled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseDetailsResponse) Reset() {
	*x = GetCourseDetailsResponse{}
	mi := &file_course_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseDetailsResponse) ProtoMessage() {}

func (x *GetCourseDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetCourseDetailsResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{12}
}

func (x *GetCourseDetailsResponse) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

func (x *GetCourseDetailsResponse) GetSections() []*Section {
	if x != nil {
		return x.Sections
	}
	return nil
}

func (x *GetCourseDetailsResponse) GetIsEnrolled() bool {
	if x != nil {
		return x.IsEnrolled
	}
	return false
}

type EnrollCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CourseId      int64                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollCourseRequest) Reset() {
	*x = EnrollCourseRequest{}
	mi := &file_course_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollCourseRequest) ProtoMessage() {}

func (x *EnrollCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollCourseRequest.ProtoReflect.Descriptor instead.
func (*EnrollCourseRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{13}
}

func (x *EnrollCourseRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *EnrollCourseRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

type EnrollCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollCourseResponse) Reset() {
	*x = EnrollCourseResponse{}
	mi := &file_course_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollCourseResponse) ProtoMessage() {}

func (x *EnrollCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollCourseResponse.ProtoReflect.Descriptor instead.
func (*EnrollCourseResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{14}
}

func (x *EnrollCourseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetMyCoursesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyCoursesRequest) Reset() {
	*x = GetMyCoursesRequest{}
	mi := &file_course_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyCoursesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyCoursesRequest) ProtoMessage() {}

func (x *GetMyCoursesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyCoursesRequest.ProtoReflect.Descriptor instead.
func (*GetMyCoursesRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{15}
}

func (x *GetMyCoursesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetMyCoursesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courses       []*Course              `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyCoursesResponse) Reset() {
	*x = GetMyCoursesResponse{}
	mi := &file_course_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyCoursesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyCoursesResponse) ProtoMessage() {}

func (x *GetMyCoursesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyCoursesResponse.ProtoReflect.Descriptor instead.
func (*GetMyCoursesResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{16}
}

func (x *GetMyCoursesResponse) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

type MarkLessonCompletedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LessonId      int64                  `protobuf:"varint,2,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkLessonCompletedRequest) Reset() {
	*x = MarkLessonCompletedRequest{}
	mi := &file_course_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkLessonCompletedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkLessonCompletedRequest) ProtoMessage() {}

func (x *MarkLessonCompletedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkLessonCompletedRequest.ProtoReflect.Descriptor instead.
func (*MarkLessonCompletedRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{17}
}

func (x *MarkLessonCompletedRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MarkLessonCompletedRequest) GetLessonId() int64 {
	if x != nil {
		return x.LessonId
	}
	return 0
}

type MarkLessonCompletedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkLessonCompletedResponse) Reset() {
	*x = MarkLessonCompletedResponse{}
	mi := &file_course_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkLessonCompletedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkLessonCompletedResponse) ProtoMessage() {}

func (x *MarkLessonCompletedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkLessonCompletedResponse.ProtoReflect.Descriptor instead.
func (*MarkLessonCompletedResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{18}
}

func (x *MarkLessonCompletedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetUploadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SectionId     int64                  `protobuf:"varint,3,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadURLRequest) Reset() {
	*x = GetUploadURLRequest{}
	mi := &file_course_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadURLRequest) ProtoMessage() {}

func (x *GetUploadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadURLRequest.ProtoReflect.Descriptor instead.
func (*GetUploadURLRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{19}
}

func (x *GetUploadURLRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GetUploadURLRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *GetUploadURLRequest) GetSectionId() int64 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

type GetUploadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadUrl     string                 `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	FinalUrl      string                 `protobuf:"bytes,2,opt,name=final_url,json=finalUrl,proto3" json:"final_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadURLResponse) Reset() {
	*x = GetUploadURLResponse{}
	mi := &file_course_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadURLResponse) ProtoMessage() {}

func (x *GetUploadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadURLResponse.ProtoReflect.Descriptor instead.
func (*GetUploadURLResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{20}
}

func (x *GetUploadURLResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *GetUploadURLResponse) GetFinalUrl() string {
	if x != nil {
		return x.FinalUrl
	}
	return ""
}

type UpdateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IsPublished   bool                   `protobuf:"varint,4,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,6,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourseRequest) Reset() {
	*x = UpdateCourseRequest{}
	mi := &file_course_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseRequest) ProtoMessage() {}

func (x *UpdateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseRequest.ProtoReflect.Descriptor instead.
func (*UpdateCourseRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateCourseRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *UpdateCourseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateCourseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCourseRequest) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

func (x *UpdateCourseRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateCourseRequest) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

type UpdateCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourseResponse) Reset() {
	*x = UpdateCourseResponse{}
	mi := &file_course_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseResponse) ProtoMessage() {}

func (x *UpdateCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseResponse.ProtoReflect.Descriptor instead.
func (*UpdateCourseResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateCourseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateSectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionId     int64                  `protobuf:"varint,1,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSectionRequest) Reset() {
	*x = UpdateSectionRequest{}
	mi := &file_course_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSectionRequest) ProtoMessage() {}

func (x *UpdateSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSectionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSectionRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateSectionRequest) GetSectionId() int64 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

func (x *UpdateSectionRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type UpdateSectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSectionResponse) Reset() {
	*x = UpdateSectionResponse{}
	mi := &file_course_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSectionResponse) ProtoMessage() {}

func (x *UpdateSectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSectionResponse.ProtoReflect.Descriptor instead.
func (*UpdateSectionResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateSectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteSectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SectionId     int64                  `protobuf:"varint,1,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSectionRequest) Reset() {
	*x = DeleteSectionRequest{}
	mi := &file_course_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSectionRequest) ProtoMessage() {}

func (x *DeleteSectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSectionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSectionRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteSectionRequest) GetSectionId() int64 {
	if x != nil {
		return x.SectionId
	}
	return 0
}

type DeleteSectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSectionResponse) Reset() {
	*x = DeleteSectionResponse{}
	mi := &file_course_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSectionResponse) ProtoMessage() {}

func (x *DeleteSectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSectionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSectionResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteSectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonId      int64                  `protobuf:"varint,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLessonRequest) Reset() {
	*x = DeleteLessonRequest{}
	mi := &file_course_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLessonRequest) ProtoMessage() {}

func (x *DeleteLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLessonRequest.ProtoReflect.Descriptor instead.
func (*DeleteLessonRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteLessonRequest) GetLessonId() int64 {
	if x != nil {
		return x.LessonId
	}
	return 0
}

type DeleteLessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLessonResponse) Reset() {
	*x = DeleteLessonResponse{}
	mi := &file_course_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLessonResponse) ProtoMessage() {}

func (x *DeleteLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLessonResponse.ProtoReflect.Descriptor instead.
func (*DeleteLessonResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteLessonResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonId      int64                  `protobuf:"varint,1,opt,name=lesson_id,json=lessonId,proto3" json:"lesson_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ContentUrl    string                 `protobuf:"bytes,3,opt,name=content_url,json=contentUrl,proto3" json:"content_url,omitempty"`
	LessonType    string                 `protobuf:"bytes,4,opt,name=lesson_type,json=lessonType,proto3" json:"lesson_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLessonRequest) Reset() {
	*x = UpdateLessonRequest{}
	mi := &file_course_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLessonRequest) ProtoMessage() {}

func (x *UpdateLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLessonRequest.ProtoReflect.Descriptor instead.
func (*UpdateLessonRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateLessonRequest) GetLessonId() int64 {
	if x != nil {
		return x.LessonId
	}
	return 0
}

func (x *UpdateLessonRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateLessonRequest) GetContentUrl() string {
	if x != nil {
		return x.ContentUrl
	}
	return ""
}

func (x *UpdateLessonRequest) GetLessonType() string {
	if x != nil {
		return x.LessonType
	}
	return ""
}

type UpdateLessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLessonResponse) Reset() {
	*x = UpdateLessonResponse{}
	mi := &file_course_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLessonResponse) ProtoMessage() {}

func (x *UpdateLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLessonResponse.ProtoReflect.Descriptor instead.
func (*UpdateLessonResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateLessonResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PublishCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	IsPublished   bool                   `protobuf:"varint,2,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"` // true = publish, false = unpublish
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishCourseRequest) Reset() {
	*x = PublishCourseRequest{}
	mi := &file_course_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishCourseRequest) ProtoMessage() {}

func (x *PublishCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishCourseRequest.ProtoReflect.Descriptor instead.
func (*PublishCourseRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{31}
}

func (x *PublishCourseRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *PublishCourseRequest) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

type PublishCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishCourseResponse) Reset() {
	*x = PublishCourseResponse{}
	mi := &file_course_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishCourseResponse) ProtoMessage() {}

func (x *PublishCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishCourseResponse.ProtoReflect.Descriptor instead.
func (*PublishCourseResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{32}
}

func (x *PublishCourseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetCourseCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseCountRequest) Reset() {
	*x = GetCourseCountRequest{}
	mi := &file_course_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseCountRequest) ProtoMessage() {}

func (x *GetCourseCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseCountRequest.ProtoReflect.Descriptor instead.
func (*GetCourseCountRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{33}
}

type GetCourseCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseCountResponse) Reset() {
	*x = GetCourseCountResponse{}
	mi := &file_course_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseCountResponse) ProtoMessage() {}

func (x *GetCourseCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseCountResponse.ProtoReflect.Descriptor instead.
func (*GetCourseCountResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{34}
}

func (x *GetCourseCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DeleteCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int64                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseRequest) Reset() {
	*x = DeleteCourseRequest{}
	mi := &file_course_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseRequest) ProtoMessage() {}

func (x *DeleteCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseRequest.ProtoReflect.Descriptor instead.
func (*DeleteCourseRequest) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{35}
}

func (x *DeleteCourseRequest) GetCourseId() int64 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

type DeleteCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseResponse) Reset() {
	*x = DeleteCourseResponse{}
	mi := &file_course_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseResponse) ProtoMessage() {}

func (x *DeleteCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_course_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseResponse.ProtoReflect.Descriptor instead.
func (*DeleteCourseResponse) Descriptor() ([]byte, []int) {
	return file_course_proto_rawDescGZIP(), []int{36}
}

func (x *DeleteCourseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_course_proto protoreflect.FileDescriptor

const file_course_proto_rawDesc = "" +
	"\n" +
	"\fcourse.proto\x12\x06course\"\xd3\x01\n" +
	"\x06Course\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rinstructor_id\x18\x04 \x01(\x03R\finstructorId\x12#\n" +
	"\rthumbnail_url\x18\x05 \x01(\tR\fthumbnailUrl\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12!\n" +
	"\fis_published\x18\a \x01(\bR\visPublished\"\x97\x01\n" +
	"\aSection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x03R\bcourseId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1f\n" +
	"\vorder_index\x18\x04 \x01(\x05R\n" +
	"orderIndex\x12(\n" +
	"\alessons\x18\x05 \x03(\v2\x0e.course.LessonR\alessons\"\xd3\x01\n" +
	"\x06Lesson\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"section_id\x18\x02 \x01(\x03R\tsectionId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1f\n" +
	"\vlesson_type\x18\x04 \x01(\tR\n" +
	"lessonType\x12\x1f\n" +
	"\vcontent_url\x18\x05 \x01(\tR\n" +
	"contentUrl\x12\x1f\n" +
	"\vorder_index\x18\x06 \x01(\x05R\n" +
	"orderIndex\x12!\n" +
	"\fis_completed\x18\a \x01(\bR\visCompleted\"\xad\x01\n" +
	"\x13CreateCourseRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12#\n" +
	"\rinstructor_id\x18\x03 \x01(\x03R\finstructorId\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12#\n" +
	"\rthumbnail_url\x18\x05 \x01(\tR\fthumbnailUrl\">\n" +
	"\x14CreateCourseResponse\x12&\n" +
	"\x06course\x18\x01 \x01(\v2\x0e.course.CourseR\x06course\"j\n" +
	"\x14CreateSectionRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x03R\bcourseId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\vorder_index\x18\x03 \x01(\x05R\n" +
	"orderIndex\"B\n" +
	"\x15CreateSectionResponse\x12)\n" +
	"\asection\x18\x01 \x01(\v2\x0f.course.SectionR\asection\"\xad\x01\n" +
	"\x13CreateLessonRequest\x12\x1d\n" +
	"\n" +
	"section_id\x18\x01 \x01(\x03R\tsectionId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\vlesson_type\x18\x03 \x01(\tR\n" +
	"lessonType\x12\x1f\n" +
	"\vcontent_url\x18\x04 \x01(\tR\n" +
	"contentUrl\x12\x1f\n" +
	"\vorder_index\x18\x05 \x01(\x05R\n" +
	"orderIndex\">\n" +
	"\x14CreateLessonResponse\x12&\n" +
	"\x06lesson\x18\x01 \x01(\v2\x0e.course.LessonR\x06lesson\"\xcd\x01\n" +
	"\x11GetCoursesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x1b\n" +
	"\tmin_price\x18\x04 \x01(\x01R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x05 \x01(\x01R\bmaxPrice\x12\x17\n" +
	"\asort_by\x18\x06 \x01(\tR\x06sortBy\x12#\n" +
	"\rinstructor_id\x18\a \x01(\x03R\finstructorId\"\x89\x01\n" +
	"\x12GetCoursesResponse\x12(\n" +
	"\acourses\x18\x01 \x03(\v2\x0e.course.CourseR\acourses\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"O\n" +
	"\x17GetCourseDetailsRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x03R\bcourseId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x90\x01\n" +
	"\x18GetCourseDetailsResponse\x12&\n" +
	"\x06course\x18\x01 \x01(\v2\x0e.course.CourseR\x06course\x12+\n" +
	"\bsections\x18\x02 \x03(\v2\x0f.course.SectionR\bsections\x12\x1f\n" +
	"\vis_enrolled\x18\x03 \x01(\bR\n" +
	"isEnrolled\"K\n" +
	"\x13EnrollCourseRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x03R\bcourseId\"0\n" +
	"\x14EnrollCourseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\".\n" +
	"\x13GetMyCoursesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"@\n" +
	"\x14GetMyCoursesResponse\x12(\n" +
	"\acourses\x18\x01 \x03(\v2\x0e.course.CourseR\acourses\"R\n" +
	"\x1aMarkLessonCompletedRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tlesson_id\x18\x02 \x01(\x03R\blessonId\"7\n" +
	"\x1bMarkLessonCompletedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"t\n" +
	"\x13GetUploadURLRequest\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"section_id\x18\x03 \x01(\x03R\tsectionId\"R\n" +
	"\x14GetUploadURLResponse\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x01 \x01(\tR\tuploadUrl\x12\x1b\n" +
	"\tfinal_url\x18\x02 \x01(\tR\bfinalUrl\"\xc8\x01\n" +
	"\x13UpdateCourseRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x03R\bcourseId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12!\n" +
	"\fis_published\x18\x04 \x01(\bR\visPublished\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12#\n" +
	"\rthumbnail_url\x18\x06 \x01(\tR\fthumbnailUrl\"0\n" +
	"\x14UpdateCourseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"K\n" +
	"\x14UpdateSectionRequest\x12\x1d\n" +
	"\n" +
	"section_id\x18\x01 \x01(\x03R\tsectionId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"1\n" +
	"\x15UpdateSectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x14DeleteSectionRequest\x12\x1d\n" +
	"\n" +
	"section_id\x18\x01 \x01(\x03R\tsectionId\"1\n" +
	"\x15DeleteSectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"2\n" +
	"\x13DeleteLessonRequest\x12\x1b\n" +
	"\tlesson_id\x18\x01 \x01(\x03R\blessonId\"0\n" +
	"\x14DeleteLessonResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8a\x01\n" +
	"\x13UpdateLessonRequest\x12\x1b\n" +
	"\tlesson_id\x18\x01 \x01(\x03R\blessonId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\vcontent_url\x18\x03 \x01(\tR\n" +
	"contentUrl\x12\x1f\n" +
	"\vlesson_type\x18\x04 \x01(\tR\n" +
	"lessonType\"0\n" +
	"\x14UpdateLessonResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"V\n" +
	"\x14PublishCourseRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x03R\bcourseId\x12!\n" +
	"\fis_published\x18\x02 \x01(\bR\visPublished\"1\n" +
	"\x15PublishCourseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x17\n" +
	"\x15GetCourseCountRequest\".\n" +
	"\x16GetCourseCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"2\n" +
	"\x13DeleteCourseRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x03R\bcourseId\"0\n" +
	"\x14DeleteCourseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xb7\n" +
	"\n" +
	"\rCourseService\x12I\n" +
	"\fCreateCourse\x12\x1b.course.CreateCourseRequest\x1a\x1c.course.CreateCourseResponse\x12L\n" +
	"\rCreateSection\x12\x1c.course.CreateSectionRequest\x1a\x1d.course.CreateSectionResponse\x12I\n" +
	"\fCreateLesson\x12\x1b.course.CreateLessonRequest\x1a\x1c.course.CreateLessonResponse\x12C\n" +
	"\n" +
	"GetCourses\x12\x19.course.GetCoursesRequest\x1a\x1a.course.GetCoursesResponse\x12U\n" +
	"\x10GetCourseDetails\x12\x1f.course.GetCourseDetailsRequest\x1a .course.GetCourseDetailsResponse\x12I\n" +
	"\fEnrollCourse\x12\x1b.course.EnrollCourseRequest\x1a\x1c.course.EnrollCourseResponse\x12I\n" +
	"\fGetMyCourses\x12\x1b.course.GetMyCoursesRequest\x1a\x1c.course.GetMyCoursesResponse\x12^\n" +
	"\x13MarkLessonCompleted\x12\".course.MarkLessonCompletedRequest\x1a#.course.MarkLessonCompletedResponse\x12I\n" +
	"\fGetUploadURL\x12\x1b.course.GetUploadURLRequest\x1a\x1c.course.GetUploadURLResponse\x12I\n" +
	"\fUpdateCourse\x12\x1b.course.UpdateCourseRequest\x1a\x1c.course.UpdateCourseResponse\x12L\n" +
	"\rUpdateSection\x12\x1c.course.UpdateSectionRequest\x1a\x1d.course.UpdateSectionResponse\x12L\n" +
	"\rDeleteSection\x12\x1c.course.DeleteSectionRequest\x1a\x1d.course.DeleteSectionResponse\x12I\n" +
	"\fDeleteLesson\x12\x1b.course.DeleteLessonRequest\x1a\x1c.course.DeleteLessonResponse\x12I\n" +
	"\fUpdateLesson\x12\x1b.course.UpdateLessonRequest\x1a\x1c.course.UpdateLessonResponse\x12L\n" +
	"\rPublishCourse\x12\x1c.course.PublishCourseRequest\x1a\x1d.course.PublishCourseResponse\x12O\n" +
	"\x0eGetCourseCount\x12\x1d.course.GetCourseCountRequest\x1a\x1e.course.GetCourseCountResponse\x12I\n" +
	"\fDeleteCourse\x12\x1b.course.DeleteCourseRequest\x1a\x1c.course.DeleteCourseResponseB\x1cZ\x1ashared/proto/course;courseb\x06proto3"

var (
	file_course_proto_rawDescOnce sync.Once
	file_course_proto_rawDescData []byte
)

func file_course_proto_rawDescGZIP() []byte {
	file_course_proto_rawDescOnce.Do(func() {
		file_course_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_course_proto_rawDesc), len(file_course_proto_rawDesc)))
	})
	return file_course_proto_rawDescData
}

var file_course_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_course_proto_goTypes = []any{
	(*Course)(nil),                      // 0: course.Course
	(*Section)(nil),                     // 1: course.Section
	(*Lesson)(nil),                      // 2: course.Lesson
	(*CreateCourseRequest)(nil),         // 3: course.CreateCourseRequest
	(*CreateCourseResponse)(nil),        // 4: course.CreateCourseResponse
	(*CreateSectionRequest)(nil),        // 5: course.CreateSectionRequest
	(*CreateSectionResponse)(nil),       // 6: course.CreateSectionResponse
	(*CreateLessonRequest)(nil),         // 7: course.CreateLessonRequest
	(*CreateLessonResponse)(nil),        // 8: course.CreateLessonResponse
	(*GetCoursesRequest)(nil),           // 9: course.GetCoursesRequest
	(*GetCoursesResponse)(nil),          // 10: course.GetCoursesResponse
	(*GetCourseDetailsRequest)(nil),     // 11: course.GetCourseDetailsRequest
	(*GetCourseDetailsResponse)(nil),    // 12: course.GetCourseDetailsResponse
	(*EnrollCourseRequest)(nil),         // 13: course.EnrollCourseRequest
	(*EnrollCourseResponse)(nil),        // 14: course.EnrollCourseResponse
	(*GetMyCoursesRequest)(nil),         // 15: course.GetMyCoursesRequest
	(*GetMyCoursesResponse)(nil),        // 16: course.GetMyCoursesResponse
	(*MarkLessonCompletedRequest)(nil),  // 17: course.MarkLessonCompletedRequest
	(*MarkLessonCompletedResponse)(nil), // 18: course.MarkLessonCompletedResponse
	(*GetUploadURLRequest)(nil),         // 19: course.GetUploadURLRequest
	(*GetUploadURLResponse)(nil),        // 20: course.GetUploadURLResponse
	(*UpdateCourseRequest)(nil),         // 21: course.UpdateCourseRequest
	(*UpdateCourseResponse)(nil),        // 22: course.UpdateCourseResponse
	(*UpdateSectionRequest)(nil),        // 23: course.UpdateSectionRequest
	(*UpdateSectionResponse)(nil),       // 24: course.UpdateSectionResponse
	(*DeleteSectionRequest)(nil),        // 25: course.DeleteSectionRequest
	(*DeleteSectionResponse)(nil),       // 26: course.DeleteSectionResponse
	(*DeleteLessonRequest)(nil),         // 27: course.DeleteLessonRequest
	(*DeleteLessonResponse)(nil),        // 28: course.DeleteLessonResponse
	(*UpdateLessonRequest)(nil),         // 29: course.UpdateLessonRequest
	(*UpdateLessonResponse)(nil),        // 30: course.UpdateLessonResponse
	(*PublishCourseRequest)(nil),        // 31: course.PublishCourseRequest
	(*PublishCourseResponse)(nil),       // 32: course.PublishCourseResponse
	(*GetCourseCountRequest)(nil),       // 33: course.GetCourseCountRequest
	(*GetCourseCountResponse)(nil),      // 34: course.GetCourseCountResponse
	(*DeleteCourseRequest)(nil),         // 35: course.DeleteCourseRequest
	(*DeleteCourseResponse)(nil),        // 36: course.DeleteCourseResponse
}
var file_course_proto_depIdxs = []int32{
	2,  // 0: course.Section.lessons:type_name -> course.Lesson
	0,  // 1: course.CreateCourseResponse.course:type_name -> course.Course
	1,  // 2: course.CreateSectionResponse.section:type_name -> course.Section
	2,  // 3: course.CreateLessonResponse.lesson:type_name -> course.Lesson
	0,  // 4: course.GetCoursesResponse.courses:type_name -> course.Course
	0,  // 5: course.GetCourseDetailsResponse.course:type_name -> course.Course
	1,  // 6: course.GetCourseDetailsResponse.sections:type_name -> course.Section
	0,  // 7: course.GetMyCoursesResponse.courses:type_name -> course.Course
	3,  // 8: course.CourseService.CreateCourse:input_type -> course.CreateCourseRequest
	5,  // 9: course.CourseService.CreateSection:input_type -> course.CreateSectionRequest
	7,  // 10: course.CourseService.CreateLesson:input_type -> course.CreateLessonRequest
	9,  // 11: course.CourseService.GetCourses:input_type -> course.GetCoursesRequest
	11, // 12: course.CourseService.GetCourseDetails:input_type -> course.GetCourseDetailsRequest
	13, // 13: course.CourseService.EnrollCourse:input_type -> course.EnrollCourseRequest
	15, // 14: course.CourseService.GetMyCourses:input_type -> course.GetMyCoursesRequest
	17, // 15: course.CourseService.MarkLessonCompleted:input_type -> course.MarkLessonCompletedRequest
	19, // 16: course.CourseService.GetUploadURL:input_type -> course.GetUploadURLRequest
	21, // 17: course.CourseService.UpdateCourse:input_type -> course.UpdateCourseRequest
	23, // 18: course.CourseService.UpdateSection:input_type -> course.UpdateSectionRequest
	25, // 19: course.CourseService.DeleteSection:input_type -> course.DeleteSectionRequest
	27, // 20: course.CourseService.DeleteLesson:input_type -> course.DeleteLessonRequest
	29, // 21: course.CourseService.UpdateLesson:input_type -> course.UpdateLessonRequest
	31, // 22: course.CourseService.PublishCourse:input_type -> course.PublishCourseRequest
	33, // 23: course.CourseService.GetCourseCount:input_type -> course.GetCourseCountRequest
	35, // 24: course.CourseService.DeleteCourse:input_type -> course.DeleteCourseRequest
	4,  // 25: course.CourseService.CreateCourse:output_type -> course.CreateCourseResponse
	6,  // 26: course.CourseService.CreateSection:output_type -> course.CreateSectionResponse
	8,  // 27: course.CourseService.CreateLesson:output_type -> course.CreateLessonResponse
	10, // 28: course.CourseService.GetCourses:output_type -> course.GetCoursesResponse
	12, // 29: course.CourseService.GetCourseDetails:output_type -> course.GetCourseDetailsResponse
	14, // 30: course.CourseService.EnrollCourse:output_type -> course.EnrollCourseResponse
	16, // 31: course.CourseService.GetMyCourses:output_type -> course.GetMyCoursesResponse
	18, // 32: course.CourseService.MarkLessonCompleted:output_type -> course.MarkLessonCompletedResponse
	20, // 33: course.CourseService.GetUploadURL:output_type -> course.GetUploadURLResponse
	22, // 34: course.CourseService.UpdateCourse:output_type -> course.UpdateCourseResponse
	24, // 35: course.CourseService.UpdateSection:output_type -> course.UpdateSectionResponse
	26, // 36: course.CourseService.DeleteSection:output_type -> course.DeleteSectionResponse
	28, // 37: course.CourseService.DeleteLesson:output_type -> course.DeleteLessonResponse
	30, // 38: course.CourseService.UpdateLesson:output_type -> course.UpdateLessonResponse
	32, // 39: course.CourseService.PublishCourse:output_type -> course.PublishCourseResponse
	34, // 40: course.CourseService.GetCourseCount:output_type -> course.GetCourseCountResponse
	36, // 41: course.CourseService.DeleteCourse:output_type -> course.DeleteCourseResponse
	25, // [25:42] is the sub-list for method output_type
	8,  // [8:25] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_course_proto_init() }
func file_course_proto_init() {
	if File_course_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_course_proto_rawDesc), len(file_course_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_course_proto_goTypes,
		DependencyIndexes: file_course_proto_depIdxs,
		MessageInfos:      file_course_proto_msgTypes,
	}.Build()
	File_course_proto = out.File
	file_course_proto_goTypes = nil
	file_course_proto_depIdxs = nil
}
