// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: ai.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateQuestionsFromAIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ContentText   string                 `protobuf:"bytes,2,opt,name=content_text,json=contentText,proto3" json:"content_text,omitempty"` // Nội dung bóc tách được từ docx/pptx
	FileUrl       string                 `protobuf:"bytes,3,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`             // URL file PDF trên cloud nếu muốn dùng Gemini File API (tuỳ chọn)
	QuestionCount int32                  `protobuf:"varint,4,opt,name=question_count,json=questionCount,proto3" json:"question_count,omitempty"`
	Difficulty    string                 `protobuf:"bytes,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	QuestionType  string                 `protobuf:"bytes,6,opt,name=question_type,json=questionType,proto3" json:"question_type,omitempty"`
	FileBytes     []byte                 `protobuf:"bytes,7,opt,name=file_bytes,json=fileBytes,proto3" json:"file_bytes,omitempty"` // Truyền trực tiếp PDF hoặc DOCX qua RPC
	FileName      string                 `protobuf:"bytes,8,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MimeType      string                 `protobuf:"bytes,9,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`         // application/pdf, application/vnd.openxmlformats-officedocument.wordprocessingml.document
	FocusTopic    string                 `protobuf:"bytes,10,opt,name=focus_topic,json=focusTopic,proto3" json:"focus_topic,omitempty"`  // Trọng tâm yêu cầu đặc biệt
	Language      string                 `protobuf:"bytes,11,opt,name=language,proto3" json:"language,omitempty"`                        // Ngôn ngữ mong muốn (VD: "Tiếng Việt")
	MaxOptions    int32                  `protobuf:"varint,12,opt,name=max_options,json=maxOptions,proto3" json:"max_options,omitempty"` // Số lượng đáp án tối đa cho mỗi câu hỏi
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateQuestionsFromAIRequest) Reset() {
	*x = GenerateQuestionsFromAIRequest{}
	mi := &file_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQuestionsFromAIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQuestionsFromAIRequest) ProtoMessage() {}

func (x *GenerateQuestionsFromAIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQuestionsFromAIRequest.ProtoReflect.Descriptor instead.
func (*GenerateQuestionsFromAIRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateQuestionsFromAIRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GenerateQuestionsFromAIRequest) GetContentText() string {
	if x != nil {
		return x.ContentText
	}
	return ""
}

func (x *GenerateQuestionsFromAIRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *GenerateQuestionsFromAIRequest) GetQuestionCount() int32 {
	if x != nil {
		return x.QuestionCount
	}
	return 0
}

func (x *GenerateQuestionsFromAIRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *GenerateQuestionsFromAIRequest) GetQuestionType() string {
	if x != nil {
		return x.QuestionType
	}
	return ""
}

func (x *GenerateQuestionsFromAIRequest) GetFileBytes() []byte {
	if x != nil {
		return x.FileBytes
	}
	return nil
}

func (x *GenerateQuestionsFromAIRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GenerateQuestionsFromAIRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *GenerateQuestionsFromAIRequest) GetFocusTopic() string {
	if x != nil {
		return x.FocusTopic
	}
	return ""
}

func (x *GenerateQuestionsFromAIRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *GenerateQuestionsFromAIRequest) GetMaxOptions() int32 {
	if x != nil {
		return x.MaxOptions
	}
	return 0
}

type GeneratedChoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	IsCorrect     bool                   `protobuf:"varint,2,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratedChoice) Reset() {
	*x = GeneratedChoice{}
	mi := &file_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratedChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedChoice) ProtoMessage() {}

func (x *GeneratedChoice) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedChoice.ProtoReflect.Descriptor instead.
func (*GeneratedChoice) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{1}
}

func (x *GeneratedChoice) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GeneratedChoice) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

type GeneratedAIQuestion struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	QuestionText string                 `protobuf:"bytes,1,opt,name=question_text,json=questionText,proto3" json:"question_text,omitempty"`
	// Deprecated: Marked as deprecated in ai.proto.
	Options []string `protobuf:"bytes,2,rep,name=options,proto3" json:"options,omitempty"`
	// Deprecated: Marked as deprecated in ai.proto.
	CorrectAnswer string             `protobuf:"bytes,3,opt,name=correct_answer,json=correctAnswer,proto3" json:"correct_answer,omitempty"`
	Explanation   string             `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"`
	Difficulty    string             `protobuf:"bytes,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Choices       []*GeneratedChoice `protobuf:"bytes,6,rep,name=choices,proto3" json:"choices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratedAIQuestion) Reset() {
	*x = GeneratedAIQuestion{}
	mi := &file_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratedAIQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedAIQuestion) ProtoMessage() {}

func (x *GeneratedAIQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedAIQuestion.ProtoReflect.Descriptor instead.
func (*GeneratedAIQuestion) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{2}
}

func (x *GeneratedAIQuestion) GetQuestionText() string {
	if x != nil {
		return x.QuestionText
	}
	return ""
}

// Deprecated: Marked as deprecated in ai.proto.
func (x *GeneratedAIQuestion) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

// Deprecated: Marked as deprecated in ai.proto.
func (x *GeneratedAIQuestion) GetCorrectAnswer() string {
	if x != nil {
		return x.CorrectAnswer
	}
	return ""
}

func (x *GeneratedAIQuestion) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *GeneratedAIQuestion) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *GeneratedAIQuestion) GetChoices() []*GeneratedChoice {
	if x != nil {
		return x.Choices
	}
	return nil
}

type GenerateQuestionsFromAIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Questions     []*GeneratedAIQuestion `protobuf:"bytes,3,rep,name=questions,proto3" json:"questions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateQuestionsFromAIResponse) Reset() {
	*x = GenerateQuestionsFromAIResponse{}
	mi := &file_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQuestionsFromAIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQuestionsFromAIResponse) ProtoMessage() {}

func (x *GenerateQuestionsFromAIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQuestionsFromAIResponse.ProtoReflect.Descriptor instead.
func (*GenerateQuestionsFromAIResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateQuestionsFromAIResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GenerateQuestionsFromAIResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GenerateQuestionsFromAIResponse) GetQuestions() []*GeneratedAIQuestion {
	if x != nil {
		return x.Questions
	}
	return nil
}

var File_ai_proto protoreflect.FileDescriptor

const file_ai_proto_rawDesc = "" +
	"\n" +
	"\bai.proto\x12\x02ai\"\x97\x03\n" +
	"\x1eGenerateQuestionsFromAIRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12!\n" +
	"\fcontent_text\x18\x02 \x01(\tR\vcontentText\x12\x19\n" +
	"\bfile_url\x18\x03 \x01(\tR\afileUrl\x12%\n" +
	"\x0equestion_count\x18\x04 \x01(\x05R\rquestionCount\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\tR\n" +
	"difficulty\x12#\n" +
	"\rquestion_type\x18\x06 \x01(\tR\fquestionType\x12\x1d\n" +
	"\n" +
	"file_bytes\x18\a \x01(\fR\tfileBytes\x12\x1b\n" +
	"\tfile_name\x18\b \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\t \x01(\tR\bmimeType\x12\x1f\n" +
	"\vfocus_topic\x18\n" +
	" \x01(\tR\n" +
	"focusTopic\x12\x1a\n" +
	"\blanguage\x18\v \x01(\tR\blanguage\x12\x1f\n" +
	"\vmax_options\x18\f \x01(\x05R\n" +
	"maxOptions\"J\n" +
	"\x0fGeneratedChoice\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x02 \x01(\bR\tisCorrect\"\xf4\x01\n" +
	"\x13GeneratedAIQuestion\x12#\n" +
	"\rquestion_text\x18\x01 \x01(\tR\fquestionText\x12\x1c\n" +
	"\aoptions\x18\x02 \x03(\tB\x02\x18\x01R\aoptions\x12)\n" +
	"\x0ecorrect_answer\x18\x03 \x01(\tB\x02\x18\x01R\rcorrectAnswer\x12 \n" +
	"\vexplanation\x18\x04 \x01(\tR\vexplanation\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\tR\n" +
	"difficulty\x12-\n" +
	"\achoices\x18\x06 \x03(\v2\x13.ai.GeneratedChoiceR\achoices\"\x8c\x01\n" +
	"\x1fGenerateQuestionsFromAIResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\tquestions\x18\x03 \x03(\v2\x17.ai.GeneratedAIQuestionR\tquestions2o\n" +
	"\tAIService\x12b\n" +
	"\x17GenerateQuestionsFromAI\x12\".ai.GenerateQuestionsFromAIRequest\x1a#.ai.GenerateQuestionsFromAIResponseB\x14Z\x12shared/proto/ai;aib\x06proto3"

var (
	file_ai_proto_rawDescOnce sync.Once
	file_ai_proto_rawDescData []byte
)

func file_ai_proto_rawDescGZIP() []byte {
	file_ai_proto_rawDescOnce.Do(func() {
		file_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)))
	})
	return file_ai_proto_rawDescData
}

var file_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ai_proto_goTypes = []any{
	(*GenerateQuestionsFromAIRequest)(nil),  // 0: ai.GenerateQuestionsFromAIRequest
	(*GeneratedChoice)(nil),                 // 1: ai.GeneratedChoice
	(*GeneratedAIQuestion)(nil),             // 2: ai.GeneratedAIQuestion
	(*GenerateQuestionsFromAIResponse)(nil), // 3: ai.GenerateQuestionsFromAIResponse
}
var file_ai_proto_depIdxs = []int32{
	1, // 0: ai.GeneratedAIQuestion.choices:type_name -> ai.GeneratedChoice
	2, // 1: ai.GenerateQuestionsFromAIResponse.questions:type_name -> ai.GeneratedAIQuestion
	0, // 2: ai.AIService.GenerateQuestionsFromAI:input_type -> ai.GenerateQuestionsFromAIRequest
	3, // 3: ai.AIService.GenerateQuestionsFromAI:output_type -> ai.GenerateQuestionsFromAIResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ai_proto_init() }
func file_ai_proto_init() {
	if File_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_proto_goTypes,
		DependencyIndexes: file_ai_proto_depIdxs,
		MessageInfos:      file_ai_proto_msgTypes,
	}.Build()
	File_ai_proto = out.File
	file_ai_proto_goTypes = nil
	file_ai_proto_depIdxs = nil
}
