// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: ai.proto

package ai

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIService_GenerateQuestionsFromAI_FullMethodName = "/ai.AIService/GenerateQuestionsFromAI"
	AIService_ExplainAnswer_FullMethodName           = "/ai.AIService/ExplainAnswer"
	AIService_ChatWithTutor_FullMethodName           = "/ai.AIService/ChatWithTutor"
)

// AIServiceClient is the client API for AIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIServiceClient interface {
	GenerateQuestionsFromAI(ctx context.Context, in *GenerateQuestionsFromAIRequest, opts ...grpc.CallOption) (*GenerateQuestionsFromAIResponse, error)
	ExplainAnswer(ctx context.Context, in *ExplainAnswerRequest, opts ...grpc.CallOption) (*ExplainAnswerResponse, error)
	ChatWithTutor(ctx context.Context, in *ChatWithTutorRequest, opts ...grpc.CallOption) (*ChatWithTutorResponse, error)
}

type aIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIServiceClient(cc grpc.ClientConnInterface) AIServiceClient {
	return &aIServiceClient{cc}
}

func (c *aIServiceClient) GenerateQuestionsFromAI(ctx context.Context, in *GenerateQuestionsFromAIRequest, opts ...grpc.CallOption) (*GenerateQuestionsFromAIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateQuestionsFromAIResponse)
	err := c.cc.Invoke(ctx, AIService_GenerateQuestionsFromAI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) ExplainAnswer(ctx context.Context, in *ExplainAnswerRequest, opts ...grpc.CallOption) (*ExplainAnswerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExplainAnswerResponse)
	err := c.cc.Invoke(ctx, AIService_ExplainAnswer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) ChatWithTutor(ctx context.Context, in *ChatWithTutorRequest, opts ...grpc.CallOption) (*ChatWithTutorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatWithTutorResponse)
	err := c.cc.Invoke(ctx, AIService_ChatWithTutor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIServiceServer is the server API for AIService service.
// All implementations must embed UnimplementedAIServiceServer
// for forward compatibility.
type AIServiceServer interface {
	GenerateQuestionsFromAI(context.Context, *GenerateQuestionsFromAIRequest) (*GenerateQuestionsFromAIResponse, error)
	ExplainAnswer(context.Context, *ExplainAnswerRequest) (*ExplainAnswerResponse, error)
	ChatWithTutor(context.Context, *ChatWithTutorRequest) (*ChatWithTutorResponse, error)
	mustEmbedUnimplementedAIServiceServer()
}

// UnimplementedAIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIServiceServer struct{}

func (UnimplementedAIServiceServer) GenerateQuestionsFromAI(context.Context, *GenerateQuestionsFromAIRequest) (*GenerateQuestionsFromAIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateQuestionsFromAI not implemented")
}
func (UnimplementedAIServiceServer) ExplainAnswer(context.Context, *ExplainAnswerRequest) (*ExplainAnswerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExplainAnswer not implemented")
}
func (UnimplementedAIServiceServer) ChatWithTutor(context.Context, *ChatWithTutorRequest) (*ChatWithTutorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChatWithTutor not implemented")
}
func (UnimplementedAIServiceServer) mustEmbedUnimplementedAIServiceServer() {}
func (UnimplementedAIServiceServer) testEmbeddedByValue()                   {}

// UnsafeAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIServiceServer will
// result in compilation errors.
type UnsafeAIServiceServer interface {
	mustEmbedUnimplementedAIServiceServer()
}

func RegisterAIServiceServer(s grpc.ServiceRegistrar, srv AIServiceServer) {
	// If the following call pancis, it indicates UnimplementedAIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIService_ServiceDesc, srv)
}

func _AIService_GenerateQuestionsFromAI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateQuestionsFromAIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GenerateQuestionsFromAI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GenerateQuestionsFromAI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GenerateQuestionsFromAI(ctx, req.(*GenerateQuestionsFromAIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_ExplainAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExplainAnswerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).ExplainAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_ExplainAnswer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).ExplainAnswer(ctx, req.(*ExplainAnswerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_ChatWithTutor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatWithTutorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).ChatWithTutor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_ChatWithTutor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).ChatWithTutor(ctx, req.(*ChatWithTutorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIService_ServiceDesc is the grpc.ServiceDesc for AIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.AIService",
	HandlerType: (*AIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateQuestionsFromAI",
			Handler:    _AIService_GenerateQuestionsFromAI_Handler,
		},
		{
			MethodName: "ExplainAnswer",
			Handler:    _AIService_ExplainAnswer_Handler,
		},
		{
			MethodName: "ChatWithTutor",
			Handler:    _AIService_ChatWithTutor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai.proto",
}
