// proto/exam.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: exam.proto

package exam

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// === Topic Messages ===
type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // Đã đổi
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_exam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{0}
}

func (x *Topic) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Topic) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_exam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTopicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTopicRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         *Topic                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicResponse) Reset() {
	*x = CreateTopicResponse{}
	mi := &file_exam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicResponse) ProtoMessage() {}

func (x *CreateTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicResponse.ProtoReflect.Descriptor instead.
func (*CreateTopicResponse) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTopicResponse) GetTopic() *Topic {
	if x != nil {
		return x.Topic
	}
	return nil
}

type GetTopicsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicsRequest) Reset() {
	*x = GetTopicsRequest{}
	mi := &file_exam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicsRequest) ProtoMessage() {}

func (x *GetTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicsRequest.ProtoReflect.Descriptor instead.
func (*GetTopicsRequest) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{3}
}

type GetTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*Topic               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicsResponse) Reset() {
	*x = GetTopicsResponse{}
	mi := &file_exam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicsResponse) ProtoMessage() {}

func (x *GetTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicsResponse.ProtoReflect.Descriptor instead.
func (*GetTopicsResponse) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{4}
}

func (x *GetTopicsResponse) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

// === Question Messages ===
type ChoiceInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	IsCorrect     bool                   `protobuf:"varint,2,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChoiceInput) Reset() {
	*x = ChoiceInput{}
	mi := &file_exam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChoiceInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChoiceInput) ProtoMessage() {}

func (x *ChoiceInput) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChoiceInput.ProtoReflect.Descriptor instead.
func (*ChoiceInput) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{5}
}

func (x *ChoiceInput) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChoiceInput) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

type CreateQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	QuestionType  string                 `protobuf:"bytes,3,opt,name=question_type,json=questionType,proto3" json:"question_type,omitempty"`
	Difficulty    string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Explanation   string                 `protobuf:"bytes,5,opt,name=explanation,proto3" json:"explanation,omitempty"`
	Choices       []*ChoiceInput         `protobuf:"bytes,6,rep,name=choices,proto3" json:"choices,omitempty"`
	CreatorId     int64                  `protobuf:"varint,7,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	ExamId        int64                  `protobuf:"varint,8,opt,name=exam_id,json=examId,proto3" json:"exam_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuestionRequest) Reset() {
	*x = CreateQuestionRequest{}
	mi := &file_exam_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionRequest) ProtoMessage() {}

func (x *CreateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionRequest.ProtoReflect.Descriptor instead.
func (*CreateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{6}
}

func (x *CreateQuestionRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *CreateQuestionRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateQuestionRequest) GetQuestionType() string {
	if x != nil {
		return x.QuestionType
	}
	return ""
}

func (x *CreateQuestionRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *CreateQuestionRequest) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *CreateQuestionRequest) GetChoices() []*ChoiceInput {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *CreateQuestionRequest) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *CreateQuestionRequest) GetExamId() int64 {
	if x != nil {
		return x.ExamId
	}
	return 0
}

type CreateQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // Đã đổi
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuestionResponse) Reset() {
	*x = CreateQuestionResponse{}
	mi := &file_exam_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuestionResponse) ProtoMessage() {}

func (x *CreateQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuestionResponse.ProtoReflect.Descriptor instead.
func (*CreateQuestionResponse) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{7}
}

func (x *CreateQuestionResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateQuestionResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// === Exam Messages ===
type CreateExamRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Title           string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	TopicId         int64                  `protobuf:"varint,3,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`                    // Đã đổi
	QuestionIds     []int64                `protobuf:"varint,4,rep,packed,name=question_ids,json=questionIds,proto3" json:"question_ids,omitempty"` // Đã đổi
	DurationMinutes int32                  `protobuf:"varint,5,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	CreatorId       int64                  `protobuf:"varint,6,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"` // Đã đổi
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateExamRequest) Reset() {
	*x = CreateExamRequest{}
	mi := &file_exam_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExamRequest) ProtoMessage() {}

func (x *CreateExamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExamRequest.ProtoReflect.Descriptor instead.
func (*CreateExamRequest) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{8}
}

func (x *CreateExamRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateExamRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateExamRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *CreateExamRequest) GetQuestionIds() []int64 {
	if x != nil {
		return x.QuestionIds
	}
	return nil
}

func (x *CreateExamRequest) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *CreateExamRequest) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

type CreateExamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // Đã đổi
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExamResponse) Reset() {
	*x = CreateExamResponse{}
	mi := &file_exam_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExamResponse) ProtoMessage() {}

func (x *CreateExamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExamResponse.ProtoReflect.Descriptor instead.
func (*CreateExamResponse) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{9}
}

func (x *CreateExamResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateExamResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// --- Dùng cho học viên làm bài ---
type ChoiceDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // Đã đổi
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChoiceDetails) Reset() {
	*x = ChoiceDetails{}
	mi := &file_exam_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChoiceDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChoiceDetails) ProtoMessage() {}

func (x *ChoiceDetails) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChoiceDetails.ProtoReflect.Descriptor instead.
func (*ChoiceDetails) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{10}
}

func (x *ChoiceDetails) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChoiceDetails) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type QuestionDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // Đã đổi
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Choices       []*ChoiceDetails       `protobuf:"bytes,3,rep,name=choices,proto3" json:"choices,omitempty"`
	QuestionType  string                 `protobuf:"bytes,4,opt,name=question_type,json=questionType,proto3" json:"question_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionDetails) Reset() {
	*x = QuestionDetails{}
	mi := &file_exam_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionDetails) ProtoMessage() {}

func (x *QuestionDetails) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionDetails.ProtoReflect.Descriptor instead.
func (*QuestionDetails) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{11}
}

func (x *QuestionDetails) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QuestionDetails) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *QuestionDetails) GetChoices() []*ChoiceDetails {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *QuestionDetails) GetQuestionType() string {
	if x != nil {
		return x.QuestionType
	}
	return ""
}

type GetExamDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExamId        int64                  `protobuf:"varint,1,opt,name=exam_id,json=examId,proto3" json:"exam_id,omitempty"` // Đã đổi
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExamDetailsRequest) Reset() {
	*x = GetExamDetailsRequest{}
	mi := &file_exam_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExamDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExamDetailsRequest) ProtoMessage() {}

func (x *GetExamDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExamDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetExamDetailsRequest) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{12}
}

func (x *GetExamDetailsRequest) GetExamId() int64 {
	if x != nil {
		return x.ExamId
	}
	return 0
}

type GetExamDetailsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // Đã đổi
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,3,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	Questions       []*QuestionDetails     `protobuf:"bytes,4,rep,name=questions,proto3" json:"questions,omitempty"`
	TopicId         int64                  `protobuf:"varint,5,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	IsPublished     bool                   `protobuf:"varint,6,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetExamDetailsResponse) Reset() {
	*x = GetExamDetailsResponse{}
	mi := &file_exam_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExamDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExamDetailsResponse) ProtoMessage() {}

func (x *GetExamDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExamDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetExamDetailsResponse) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{13}
}

func (x *GetExamDetailsResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetExamDetailsResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetExamDetailsResponse) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *GetExamDetailsResponse) GetQuestions() []*QuestionDetails {
	if x != nil {
		return x.Questions
	}
	return nil
}

func (x *GetExamDetailsResponse) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *GetExamDetailsResponse) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

// === Submission Messages ===
type UserAnswer struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QuestionId     int64                  `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`               // Đã đổi
	ChosenChoiceId int64                  `protobuf:"varint,2,opt,name=chosen_choice_id,json=chosenChoiceId,proto3" json:"chosen_choice_id,omitempty"` // Đã đổi (và giờ đây 0 có thể là "không chọn")
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserAnswer) Reset() {
	*x = UserAnswer{}
	mi := &file_exam_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAnswer) ProtoMessage() {}

func (x *UserAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAnswer.ProtoReflect.Descriptor instead.
func (*UserAnswer) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{14}
}

func (x *UserAnswer) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *UserAnswer) GetChosenChoiceId() int64 {
	if x != nil {
		return x.ChosenChoiceId
	}
	return 0
}

type SubmitExamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExamId        int64                  `protobuf:"varint,1,opt,name=exam_id,json=examId,proto3" json:"exam_id,omitempty"` // Đã đổi
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Đã đổi
	Answers       []*UserAnswer          `protobuf:"bytes,3,rep,name=answers,proto3" json:"answers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitExamRequest) Reset() {
	*x = SubmitExamRequest{}
	mi := &file_exam_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitExamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitExamRequest) ProtoMessage() {}

func (x *SubmitExamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitExamRequest.ProtoReflect.Descriptor instead.
func (*SubmitExamRequest) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{15}
}

func (x *SubmitExamRequest) GetExamId() int64 {
	if x != nil {
		return x.ExamId
	}
	return 0
}

func (x *SubmitExamRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubmitExamRequest) GetAnswers() []*UserAnswer {
	if x != nil {
		return x.Answers
	}
	return nil
}

type SubmitExamResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId   int64                  `protobuf:"varint,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"` // Đã đổi
	Score          float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	CorrectCount   int32                  `protobuf:"varint,3,opt,name=correct_count,json=correctCount,proto3" json:"correct_count,omitempty"`
	TotalQuestions int32                  `protobuf:"varint,4,opt,name=total_questions,json=totalQuestions,proto3" json:"total_questions,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitExamResponse) Reset() {
	*x = SubmitExamResponse{}
	mi := &file_exam_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitExamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitExamResponse) ProtoMessage() {}

func (x *SubmitExamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitExamResponse.ProtoReflect.Descriptor instead.
func (*SubmitExamResponse) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{16}
}

func (x *SubmitExamResponse) GetSubmissionId() int64 {
	if x != nil {
		return x.SubmissionId
	}
	return 0
}

func (x *SubmitExamResponse) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SubmitExamResponse) GetCorrectCount() int32 {
	if x != nil {
		return x.CorrectCount
	}
	return 0
}

func (x *SubmitExamResponse) GetTotalQuestions() int32 {
	if x != nil {
		return x.TotalQuestions
	}
	return 0
}

type GetSubmissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId  int64                  `protobuf:"varint,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Để kiểm tra quyền sở hữu (bảo mật)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubmissionRequest) Reset() {
	*x = GetSubmissionRequest{}
	mi := &file_exam_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubmissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubmissionRequest) ProtoMessage() {}

func (x *GetSubmissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubmissionRequest.ProtoReflect.Descriptor instead.
func (*GetSubmissionRequest) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{17}
}

func (x *GetSubmissionRequest) GetSubmissionId() int64 {
	if x != nil {
		return x.SubmissionId
	}
	return 0
}

func (x *GetSubmissionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetSubmissionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ExamTitle      string                 `protobuf:"bytes,2,opt,name=exam_title,json=examTitle,proto3" json:"exam_title,omitempty"`
	Score          float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	CorrectCount   int32                  `protobuf:"varint,4,opt,name=correct_count,json=correctCount,proto3" json:"correct_count,omitempty"`
	TotalQuestions int32                  `protobuf:"varint,5,opt,name=total_questions,json=totalQuestions,proto3" json:"total_questions,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	SubmittedAt    string                 `protobuf:"bytes,7,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"` // Trả về string ISO 8601
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSubmissionResponse) Reset() {
	*x = GetSubmissionResponse{}
	mi := &file_exam_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubmissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubmissionResponse) ProtoMessage() {}

func (x *GetSubmissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubmissionResponse.ProtoReflect.Descriptor instead.
func (*GetSubmissionResponse) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{18}
}

func (x *GetSubmissionResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetSubmissionResponse) GetExamTitle() string {
	if x != nil {
		return x.ExamTitle
	}
	return ""
}

func (x *GetSubmissionResponse) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GetSubmissionResponse) GetCorrectCount() int32 {
	if x != nil {
		return x.CorrectCount
	}
	return 0
}

func (x *GetSubmissionResponse) GetTotalQuestions() int32 {
	if x != nil {
		return x.TotalQuestions
	}
	return 0
}

func (x *GetSubmissionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetSubmissionResponse) GetSubmittedAt() string {
	if x != nil {
		return x.SubmittedAt
	}
	return ""
}

type GetExamCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExamCountRequest) Reset() {
	*x = GetExamCountRequest{}
	mi := &file_exam_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExamCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExamCountRequest) ProtoMessage() {}

func (x *GetExamCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExamCountRequest.ProtoReflect.Descriptor instead.
func (*GetExamCountRequest) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{19}
}

type GetExamCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExamCountResponse) Reset() {
	*x = GetExamCountResponse{}
	mi := &file_exam_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExamCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExamCountResponse) ProtoMessage() {}

func (x *GetExamCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExamCountResponse.ProtoReflect.Descriptor instead.
func (*GetExamCountResponse) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{20}
}

func (x *GetExamCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ExamListItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,3,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	TopicId         int64                  `protobuf:"varint,4,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	CreatorId       int64                  `protobuf:"varint,5,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	IsPublished     bool                   `protobuf:"varint,6,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExamListItem) Reset() {
	*x = ExamListItem{}
	mi := &file_exam_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExamListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExamListItem) ProtoMessage() {}

func (x *ExamListItem) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExamListItem.ProtoReflect.Descriptor instead.
func (*ExamListItem) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{21}
}

func (x *ExamListItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExamListItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ExamListItem) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *ExamListItem) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *ExamListItem) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *ExamListItem) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

type GetExamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	CreatorId     int64                  `protobuf:"varint,3,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExamsRequest) Reset() {
	*x = GetExamsRequest{}
	mi := &file_exam_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExamsRequest) ProtoMessage() {}

func (x *GetExamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExamsRequest.ProtoReflect.Descriptor instead.
func (*GetExamsRequest) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{22}
}

func (x *GetExamsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetExamsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetExamsRequest) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

type GetExamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exams         []*ExamListItem        `protobuf:"bytes,1,rep,name=exams,proto3" json:"exams,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExamsResponse) Reset() {
	*x = GetExamsResponse{}
	mi := &file_exam_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExamsResponse) ProtoMessage() {}

func (x *GetExamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExamsResponse.ProtoReflect.Descriptor instead.
func (*GetExamsResponse) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{23}
}

func (x *GetExamsResponse) GetExams() []*ExamListItem {
	if x != nil {
		return x.Exams
	}
	return nil
}

func (x *GetExamsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetExamsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetExamsResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type PublishExamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExamId        int64                  `protobuf:"varint,1,opt,name=exam_id,json=examId,proto3" json:"exam_id,omitempty"`
	IsPublished   bool                   `protobuf:"varint,2,opt,name=is_published,json=isPublished,proto3" json:"is_published,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishExamRequest) Reset() {
	*x = PublishExamRequest{}
	mi := &file_exam_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishExamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishExamRequest) ProtoMessage() {}

func (x *PublishExamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishExamRequest.ProtoReflect.Descriptor instead.
func (*PublishExamRequest) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{24}
}

func (x *PublishExamRequest) GetExamId() int64 {
	if x != nil {
		return x.ExamId
	}
	return 0
}

func (x *PublishExamRequest) GetIsPublished() bool {
	if x != nil {
		return x.IsPublished
	}
	return false
}

type PublishExamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishExamResponse) Reset() {
	*x = PublishExamResponse{}
	mi := &file_exam_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishExamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishExamResponse) ProtoMessage() {}

func (x *PublishExamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishExamResponse.ProtoReflect.Descriptor instead.
func (*PublishExamResponse) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{25}
}

func (x *PublishExamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    int64                  `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	QuestionType  string                 `protobuf:"bytes,3,opt,name=question_type,json=questionType,proto3" json:"question_type,omitempty"`
	Difficulty    string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Explanation   string                 `protobuf:"bytes,5,opt,name=explanation,proto3" json:"explanation,omitempty"`
	Choices       []*ChoiceInput         `protobuf:"bytes,6,rep,name=choices,proto3" json:"choices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuestionRequest) Reset() {
	*x = UpdateQuestionRequest{}
	mi := &file_exam_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionRequest) ProtoMessage() {}

func (x *UpdateQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuestionRequest) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateQuestionRequest) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

func (x *UpdateQuestionRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateQuestionRequest) GetQuestionType() string {
	if x != nil {
		return x.QuestionType
	}
	return ""
}

func (x *UpdateQuestionRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *UpdateQuestionRequest) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *UpdateQuestionRequest) GetChoices() []*ChoiceInput {
	if x != nil {
		return x.Choices
	}
	return nil
}

type UpdateQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuestionResponse) Reset() {
	*x = UpdateQuestionResponse{}
	mi := &file_exam_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuestionResponse) ProtoMessage() {}

func (x *UpdateQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuestionResponse.ProtoReflect.Descriptor instead.
func (*UpdateQuestionResponse) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateQuestionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteQuestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    int64                  `protobuf:"varint,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuestionRequest) Reset() {
	*x = DeleteQuestionRequest{}
	mi := &file_exam_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuestionRequest) ProtoMessage() {}

func (x *DeleteQuestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuestionRequest.ProtoReflect.Descriptor instead.
func (*DeleteQuestionRequest) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteQuestionRequest) GetQuestionId() int64 {
	if x != nil {
		return x.QuestionId
	}
	return 0
}

type DeleteQuestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuestionResponse) Reset() {
	*x = DeleteQuestionResponse{}
	mi := &file_exam_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuestionResponse) ProtoMessage() {}

func (x *DeleteQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuestionResponse.ProtoReflect.Descriptor instead.
func (*DeleteQuestionResponse) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteQuestionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateExamRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExamId          int64                  `protobuf:"varint,1,opt,name=exam_id,json=examId,proto3" json:"exam_id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,4,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	TopicId         int64                  `protobuf:"varint,5,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateExamRequest) Reset() {
	*x = UpdateExamRequest{}
	mi := &file_exam_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExamRequest) ProtoMessage() {}

func (x *UpdateExamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExamRequest.ProtoReflect.Descriptor instead.
func (*UpdateExamRequest) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateExamRequest) GetExamId() int64 {
	if x != nil {
		return x.ExamId
	}
	return 0
}

func (x *UpdateExamRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateExamRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateExamRequest) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

func (x *UpdateExamRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

type UpdateExamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExamResponse) Reset() {
	*x = UpdateExamResponse{}
	mi := &file_exam_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExamResponse) ProtoMessage() {}

func (x *UpdateExamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExamResponse.ProtoReflect.Descriptor instead.
func (*UpdateExamResponse) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{31}
}

func (x *UpdateExamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteExamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExamId        int64                  `protobuf:"varint,1,opt,name=exam_id,json=examId,proto3" json:"exam_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExamRequest) Reset() {
	*x = DeleteExamRequest{}
	mi := &file_exam_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExamRequest) ProtoMessage() {}

func (x *DeleteExamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExamRequest.ProtoReflect.Descriptor instead.
func (*DeleteExamRequest) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{32}
}

func (x *DeleteExamRequest) GetExamId() int64 {
	if x != nil {
		return x.ExamId
	}
	return 0
}

type DeleteExamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExamResponse) Reset() {
	*x = DeleteExamResponse{}
	mi := &file_exam_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExamResponse) ProtoMessage() {}

func (x *DeleteExamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_exam_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExamResponse.ProtoReflect.Descriptor instead.
func (*DeleteExamResponse) Descriptor() ([]byte, []int) {
	return file_exam_proto_rawDescGZIP(), []int{33}
}

func (x *DeleteExamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_exam_proto protoreflect.FileDescriptor

const file_exam_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"exam.proto\x12\x04exam\"M\n" +
	"\x05Topic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"J\n" +
	"\x12CreateTopicRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"8\n" +
	"\x13CreateTopicResponse\x12!\n" +
	"\x05topic\x18\x01 \x01(\v2\v.exam.TopicR\x05topic\"\x12\n" +
	"\x10GetTopicsRequest\"8\n" +
	"\x11GetTopicsResponse\x12#\n" +
	"\x06topics\x18\x01 \x03(\v2\v.exam.TopicR\x06topics\"F\n" +
	"\vChoiceInput\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x02 \x01(\bR\tisCorrect\"\x98\x02\n" +
	"\x15CreateQuestionRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12#\n" +
	"\rquestion_type\x18\x03 \x01(\tR\fquestionType\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12 \n" +
	"\vexplanation\x18\x05 \x01(\tR\vexplanation\x12+\n" +
	"\achoices\x18\x06 \x03(\v2\x11.exam.ChoiceInputR\achoices\x12\x1d\n" +
	"\n" +
	"creator_id\x18\a \x01(\x03R\tcreatorId\x12\x17\n" +
	"\aexam_id\x18\b \x01(\x03R\x06examId\"B\n" +
	"\x16CreateQuestionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xd3\x01\n" +
	"\x11CreateExamRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x19\n" +
	"\btopic_id\x18\x03 \x01(\x03R\atopicId\x12!\n" +
	"\fquestion_ids\x18\x04 \x03(\x03R\vquestionIds\x12)\n" +
	"\x10duration_minutes\x18\x05 \x01(\x05R\x0fdurationMinutes\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x06 \x01(\x03R\tcreatorId\":\n" +
	"\x12CreateExamResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"9\n" +
	"\rChoiceDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x8f\x01\n" +
	"\x0fQuestionDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12-\n" +
	"\achoices\x18\x03 \x03(\v2\x13.exam.ChoiceDetailsR\achoices\x12#\n" +
	"\rquestion_type\x18\x04 \x01(\tR\fquestionType\"0\n" +
	"\x15GetExamDetailsRequest\x12\x17\n" +
	"\aexam_id\x18\x01 \x01(\x03R\x06examId\"\xdc\x01\n" +
	"\x16GetExamDetailsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12)\n" +
	"\x10duration_minutes\x18\x03 \x01(\x05R\x0fdurationMinutes\x123\n" +
	"\tquestions\x18\x04 \x03(\v2\x15.exam.QuestionDetailsR\tquestions\x12\x19\n" +
	"\btopic_id\x18\x05 \x01(\x03R\atopicId\x12!\n" +
	"\fis_published\x18\x06 \x01(\bR\visPublished\"W\n" +
	"\n" +
	"UserAnswer\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x03R\n" +
	"questionId\x12(\n" +
	"\x10chosen_choice_id\x18\x02 \x01(\x03R\x0echosenChoiceId\"q\n" +
	"\x11SubmitExamRequest\x12\x17\n" +
	"\aexam_id\x18\x01 \x01(\x03R\x06examId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12*\n" +
	"\aanswers\x18\x03 \x03(\v2\x10.exam.UserAnswerR\aanswers\"\x9d\x01\n" +
	"\x12SubmitExamResponse\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\x03R\fsubmissionId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12#\n" +
	"\rcorrect_count\x18\x03 \x01(\x05R\fcorrectCount\x12'\n" +
	"\x0ftotal_questions\x18\x04 \x01(\x05R\x0etotalQuestions\"T\n" +
	"\x14GetSubmissionRequest\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\x03R\fsubmissionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\xe5\x01\n" +
	"\x15GetSubmissionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"exam_title\x18\x02 \x01(\tR\texamTitle\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\x12#\n" +
	"\rcorrect_count\x18\x04 \x01(\x05R\fcorrectCount\x12'\n" +
	"\x0ftotal_questions\x18\x05 \x01(\x05R\x0etotalQuestions\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12!\n" +
	"\fsubmitted_at\x18\a \x01(\tR\vsubmittedAt\"\x15\n" +
	"\x13GetExamCountRequest\",\n" +
	"\x14GetExamCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"\xbc\x01\n" +
	"\fExamListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12)\n" +
	"\x10duration_minutes\x18\x03 \x01(\x05R\x0fdurationMinutes\x12\x19\n" +
	"\btopic_id\x18\x04 \x01(\x03R\atopicId\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x05 \x01(\x03R\tcreatorId\x12!\n" +
	"\fis_published\x18\x06 \x01(\bR\visPublished\"Z\n" +
	"\x0fGetExamsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x03 \x01(\x03R\tcreatorId\"\x87\x01\n" +
	"\x10GetExamsResponse\x12(\n" +
	"\x05exams\x18\x01 \x03(\v2\x12.exam.ExamListItemR\x05exams\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"P\n" +
	"\x12PublishExamRequest\x12\x17\n" +
	"\aexam_id\x18\x01 \x01(\x03R\x06examId\x12!\n" +
	"\fis_published\x18\x02 \x01(\bR\visPublished\"/\n" +
	"\x13PublishExamResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xe6\x01\n" +
	"\x15UpdateQuestionRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x03R\n" +
	"questionId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12#\n" +
	"\rquestion_type\x18\x03 \x01(\tR\fquestionType\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12 \n" +
	"\vexplanation\x18\x05 \x01(\tR\vexplanation\x12+\n" +
	"\achoices\x18\x06 \x03(\v2\x11.exam.ChoiceInputR\achoices\"2\n" +
	"\x16UpdateQuestionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"8\n" +
	"\x15DeleteQuestionRequest\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\x03R\n" +
	"questionId\"2\n" +
	"\x16DeleteQuestionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xaa\x01\n" +
	"\x11UpdateExamRequest\x12\x17\n" +
	"\aexam_id\x18\x01 \x01(\x03R\x06examId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12)\n" +
	"\x10duration_minutes\x18\x04 \x01(\x05R\x0fdurationMinutes\x12\x19\n" +
	"\btopic_id\x18\x05 \x01(\x03R\atopicId\".\n" +
	"\x12UpdateExamResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\x11DeleteExamRequest\x12\x17\n" +
	"\aexam_id\x18\x01 \x01(\x03R\x06examId\".\n" +
	"\x12DeleteExamResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xd7\a\n" +
	"\vExamService\x12B\n" +
	"\vCreateTopic\x12\x18.exam.CreateTopicRequest\x1a\x19.exam.CreateTopicResponse\x12<\n" +
	"\tGetTopics\x12\x16.exam.GetTopicsRequest\x1a\x17.exam.GetTopicsResponse\x12K\n" +
	"\x0eCreateQuestion\x12\x1b.exam.CreateQuestionRequest\x1a\x1c.exam.CreateQuestionResponse\x12?\n" +
	"\n" +
	"CreateExam\x12\x17.exam.CreateExamRequest\x1a\x18.exam.CreateExamResponse\x12K\n" +
	"\x0eGetExamDetails\x12\x1b.exam.GetExamDetailsRequest\x1a\x1c.exam.GetExamDetailsResponse\x12?\n" +
	"\n" +
	"SubmitExam\x12\x17.exam.SubmitExamRequest\x1a\x18.exam.SubmitExamResponse\x12H\n" +
	"\rGetSubmission\x12\x1a.exam.GetSubmissionRequest\x1a\x1b.exam.GetSubmissionResponse\x12E\n" +
	"\fGetExamCount\x12\x19.exam.GetExamCountRequest\x1a\x1a.exam.GetExamCountResponse\x129\n" +
	"\bGetExams\x12\x15.exam.GetExamsRequest\x1a\x16.exam.GetExamsResponse\x12B\n" +
	"\vPublishExam\x12\x18.exam.PublishExamRequest\x1a\x19.exam.PublishExamResponse\x12K\n" +
	"\x0eUpdateQuestion\x12\x1b.exam.UpdateQuestionRequest\x1a\x1c.exam.UpdateQuestionResponse\x12K\n" +
	"\x0eDeleteQuestion\x12\x1b.exam.DeleteQuestionRequest\x1a\x1c.exam.DeleteQuestionResponse\x12?\n" +
	"\n" +
	"UpdateExam\x12\x17.exam.UpdateExamRequest\x1a\x18.exam.UpdateExamResponse\x12?\n" +
	"\n" +
	"DeleteExam\x12\x17.exam.DeleteExamRequest\x1a\x18.exam.DeleteExamResponseB\x18Z\x16shared/proto/exam;examb\x06proto3"

var (
	file_exam_proto_rawDescOnce sync.Once
	file_exam_proto_rawDescData []byte
)

func file_exam_proto_rawDescGZIP() []byte {
	file_exam_proto_rawDescOnce.Do(func() {
		file_exam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_exam_proto_rawDesc), len(file_exam_proto_rawDesc)))
	})
	return file_exam_proto_rawDescData
}

var file_exam_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_exam_proto_goTypes = []any{
	(*Topic)(nil),                  // 0: exam.Topic
	(*CreateTopicRequest)(nil),     // 1: exam.CreateTopicRequest
	(*CreateTopicResponse)(nil),    // 2: exam.CreateTopicResponse
	(*GetTopicsRequest)(nil),       // 3: exam.GetTopicsRequest
	(*GetTopicsResponse)(nil),      // 4: exam.GetTopicsResponse
	(*ChoiceInput)(nil),            // 5: exam.ChoiceInput
	(*CreateQuestionRequest)(nil),  // 6: exam.CreateQuestionRequest
	(*CreateQuestionResponse)(nil), // 7: exam.CreateQuestionResponse
	(*CreateExamRequest)(nil),      // 8: exam.CreateExamRequest
	(*CreateExamResponse)(nil),     // 9: exam.CreateExamResponse
	(*ChoiceDetails)(nil),          // 10: exam.ChoiceDetails
	(*QuestionDetails)(nil),        // 11: exam.QuestionDetails
	(*GetExamDetailsRequest)(nil),  // 12: exam.GetExamDetailsRequest
	(*GetExamDetailsResponse)(nil), // 13: exam.GetExamDetailsResponse
	(*UserAnswer)(nil),             // 14: exam.UserAnswer
	(*SubmitExamRequest)(nil),      // 15: exam.SubmitExamRequest
	(*SubmitExamResponse)(nil),     // 16: exam.SubmitExamResponse
	(*GetSubmissionRequest)(nil),   // 17: exam.GetSubmissionRequest
	(*GetSubmissionResponse)(nil),  // 18: exam.GetSubmissionResponse
	(*GetExamCountRequest)(nil),    // 19: exam.GetExamCountRequest
	(*GetExamCountResponse)(nil),   // 20: exam.GetExamCountResponse
	(*ExamListItem)(nil),           // 21: exam.ExamListItem
	(*GetExamsRequest)(nil),        // 22: exam.GetExamsRequest
	(*GetExamsResponse)(nil),       // 23: exam.GetExamsResponse
	(*PublishExamRequest)(nil),     // 24: exam.PublishExamRequest
	(*PublishExamResponse)(nil),    // 25: exam.PublishExamResponse
	(*UpdateQuestionRequest)(nil),  // 26: exam.UpdateQuestionRequest
	(*UpdateQuestionResponse)(nil), // 27: exam.UpdateQuestionResponse
	(*DeleteQuestionRequest)(nil),  // 28: exam.DeleteQuestionRequest
	(*DeleteQuestionResponse)(nil), // 29: exam.DeleteQuestionResponse
	(*UpdateExamRequest)(nil),      // 30: exam.UpdateExamRequest
	(*UpdateExamResponse)(nil),     // 31: exam.UpdateExamResponse
	(*DeleteExamRequest)(nil),      // 32: exam.DeleteExamRequest
	(*DeleteExamResponse)(nil),     // 33: exam.DeleteExamResponse
}
var file_exam_proto_depIdxs = []int32{
	0,  // 0: exam.CreateTopicResponse.topic:type_name -> exam.Topic
	0,  // 1: exam.GetTopicsResponse.topics:type_name -> exam.Topic
	5,  // 2: exam.CreateQuestionRequest.choices:type_name -> exam.ChoiceInput
	10, // 3: exam.QuestionDetails.choices:type_name -> exam.ChoiceDetails
	11, // 4: exam.GetExamDetailsResponse.questions:type_name -> exam.QuestionDetails
	14, // 5: exam.SubmitExamRequest.answers:type_name -> exam.UserAnswer
	21, // 6: exam.GetExamsResponse.exams:type_name -> exam.ExamListItem
	5,  // 7: exam.UpdateQuestionRequest.choices:type_name -> exam.ChoiceInput
	1,  // 8: exam.ExamService.CreateTopic:input_type -> exam.CreateTopicRequest
	3,  // 9: exam.ExamService.GetTopics:input_type -> exam.GetTopicsRequest
	6,  // 10: exam.ExamService.CreateQuestion:input_type -> exam.CreateQuestionRequest
	8,  // 11: exam.ExamService.CreateExam:input_type -> exam.CreateExamRequest
	12, // 12: exam.ExamService.GetExamDetails:input_type -> exam.GetExamDetailsRequest
	15, // 13: exam.ExamService.SubmitExam:input_type -> exam.SubmitExamRequest
	17, // 14: exam.ExamService.GetSubmission:input_type -> exam.GetSubmissionRequest
	19, // 15: exam.ExamService.GetExamCount:input_type -> exam.GetExamCountRequest
	22, // 16: exam.ExamService.GetExams:input_type -> exam.GetExamsRequest
	24, // 17: exam.ExamService.PublishExam:input_type -> exam.PublishExamRequest
	26, // 18: exam.ExamService.UpdateQuestion:input_type -> exam.UpdateQuestionRequest
	28, // 19: exam.ExamService.DeleteQuestion:input_type -> exam.DeleteQuestionRequest
	30, // 20: exam.ExamService.UpdateExam:input_type -> exam.UpdateExamRequest
	32, // 21: exam.ExamService.DeleteExam:input_type -> exam.DeleteExamRequest
	2,  // 22: exam.ExamService.CreateTopic:output_type -> exam.CreateTopicResponse
	4,  // 23: exam.ExamService.GetTopics:output_type -> exam.GetTopicsResponse
	7,  // 24: exam.ExamService.CreateQuestion:output_type -> exam.CreateQuestionResponse
	9,  // 25: exam.ExamService.CreateExam:output_type -> exam.CreateExamResponse
	13, // 26: exam.ExamService.GetExamDetails:output_type -> exam.GetExamDetailsResponse
	16, // 27: exam.ExamService.SubmitExam:output_type -> exam.SubmitExamResponse
	18, // 28: exam.ExamService.GetSubmission:output_type -> exam.GetSubmissionResponse
	20, // 29: exam.ExamService.GetExamCount:output_type -> exam.GetExamCountResponse
	23, // 30: exam.ExamService.GetExams:output_type -> exam.GetExamsResponse
	25, // 31: exam.ExamService.PublishExam:output_type -> exam.PublishExamResponse
	27, // 32: exam.ExamService.UpdateQuestion:output_type -> exam.UpdateQuestionResponse
	29, // 33: exam.ExamService.DeleteQuestion:output_type -> exam.DeleteQuestionResponse
	31, // 34: exam.ExamService.UpdateExam:output_type -> exam.UpdateExamResponse
	33, // 35: exam.ExamService.DeleteExam:output_type -> exam.DeleteExamResponse
	22, // [22:36] is the sub-list for method output_type
	8,  // [8:22] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_exam_proto_init() }
func file_exam_proto_init() {
	if File_exam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_exam_proto_rawDesc), len(file_exam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exam_proto_goTypes,
		DependencyIndexes: file_exam_proto_depIdxs,
		MessageInfos:      file_exam_proto_msgTypes,
	}.Build()
	File_exam_proto = out.File
	file_exam_proto_goTypes = nil
	file_exam_proto_depIdxs = nil
}
